import { LegalShell } from '@/components/legal/legal-shell';

export const metadata = { title: 'Terms of Use' };

export default function TermsPage() {
  return (
    <LegalShell title="Terms of Use" updated="22 July 2026">
      <p>
        These Terms of Use govern your access to and use of Post2Hire. By creating an account
        or using our tools, you agree to these terms. This is a general template and should be
        reviewed by a qualified professional before launch.
      </p>

      <h2>Eligibility and accounts</h2>
      <p>
        You must provide a valid, verifiable email address and complete email verification
        before using either tool. You are responsible for keeping your password secure and for
        all activity under your account.
      </p>

      <h2>Marketing communications consent</h2>
      <p>
        By submitting the registration form and providing your email address, you expressly
        consent to receiving promotional and marketing communications (including newsletters,
        emails, special offers, and product updates) from Post2Hire (P2H). You may withdraw
        your consent at any time by clicking the unsubscribe link at the bottom of our emails or
        by contacting us at{' '}
        <a href="mailto:postgethired@gmail.com">postgethired@gmail.com</a>.
      </p>

      <h2>Acceptable use</h2>
      <p>
        You agree not to use Post2Hire to generate unlawful, defamatory, fraudulent, or harmful
        content; to misrepresent your identity, qualifications, or experience; to attempt to
        bypass rate limits or security controls; or to upload files containing malicious code.
      </p>

      <h2>Content you submit</h2>
      <p>
        You retain ownership of the CVs, job descriptions, and other content you submit. You
        grant us a limited license to process that content solely to provide the requested
        generation and export features.
      </p>

      <h2>AI-generated content</h2>
      <p>
        Posts, images, CVs, and cover letters are generated by AI and may contain errors. You
        are solely responsible for reviewing all output before publishing it or sending it to
        an employer. See our <a href="/disclaimer">AI Content Disclaimer</a>.
      </p>

      <h2>Fair use limits</h2>
      <p>
        To keep the service available to everyone, we apply a daily limit on the number of
        generations per account. Limits may change without notice.
      </p>

      <h2>Termination</h2>
      <p>
        We may suspend or terminate accounts that violate these terms. You may delete your own
        account at any time from Account Settings.
      </p>

      <h2>Disclaimer of warranties</h2>
      <p>
        Post2Hire is provided "as is" without warranties of any kind. We do not guarantee that
        generated content will result in job offers, engagement, or any particular outcome.
      </p>

      <h2>Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, Post2Hire is not liable for indirect,
        incidental, or consequential damages arising from your use of the service.
      </p>

      <h2>Changes to these terms</h2>
      <p>We may update these terms from time to time. Continued use after changes constitutes acceptance.</p>

      <h2>Contact</h2>
      <p>
        Questions about these terms can be sent to{' '}
        <a href="mailto:postgethired@gmail.com">postgethired@gmail.com</a>.
      </p>
    </LegalShell>
  );
}
